//! Bakes the expected monitor measurement (`H_EXPECTED: [u8; 32]`) into the
//! BROM image.
//!
//! The measured-boot build order (see `cargo xtask verilator -- measure`):
//!   1. build the monitor sim image FIRST,
//!   2. BLAKE2s-256 its MON_CODE bytes,
//!   3. write those 32 bytes to a file and point `REDOUBT_H_EXPECTED` at it,
//!   4. build THIS crate — this script reads the file and emits the const.
//!
//! If `REDOUBT_H_EXPECTED` is unset (e.g. a stray standalone build), a
//! recognisable all-`0xEE` placeholder is emitted so the crate still compiles;
//! such an image would fail its measurement and HALT (fail closed), never boot
//! a monitor.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=REDOUBT_H_EXPECTED");
    println!("cargo:rerun-if-changed=build.rs");

    let bytes: [u8; 32] = match env::var("REDOUBT_H_EXPECTED") {
        Ok(path) => {
            println!("cargo:rerun-if-changed={path}");
            let raw = fs::read(&path)
                .unwrap_or_else(|e| panic!("failed to read REDOUBT_H_EXPECTED={path}: {e}"));
            assert_eq!(
                raw.len(),
                32,
                "REDOUBT_H_EXPECTED={path} must be exactly 32 bytes (BLAKE2s-256), got {}",
                raw.len()
            );
            let mut b = [0u8; 32];
            b.copy_from_slice(&raw);
            b
        }
        Err(_) => [0xEEu8; 32],
    };

    let mut out = String::from(
        "// GENERATED by crates/brom/build.rs from $REDOUBT_H_EXPECTED.\n\
         // Do not edit; produced by the `cargo xtask verilator -- measure` flow.\n\
         pub const H_EXPECTED: [u8; 32] = [\n",
    );
    for chunk in bytes.chunks(8) {
        out.push_str("    ");
        for b in chunk {
            out.push_str(&format!("0x{b:02x}, "));
        }
        out.push('\n');
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("h_expected_gen.rs");
    fs::write(&dest, out).expect("write h_expected_gen.rs");
}
