//! Bakes the expected monitor measurement (`HASH_LEN` + `H_EXPECTED: [u8; 32]`)
//! into the BROM image.
//!
//! The measured-boot build order (see `cargo xtask verilator -- measure`):
//!   1. build the monitor sim image FIRST,
//!   2. BLAKE2s-256 its FULL loaded/executed image and record the measured length,
//!   3. write a 36-byte file (4-byte LE length + 32-byte digest) and point
//!      `REDOUBT_H_EXPECTED` at it,
//!   4. build THIS crate — this script reads the file and emits both consts.
//!
//! Both the length and the hash are single-sourced from the built ELF (via
//! `redoubt_soc.py`), so the BROM can never measure a different range than the
//! one that was hashed.
//!
//! If `REDOUBT_H_EXPECTED` is unset (e.g. a stray standalone build), a
//! recognisable all-`0xEE` placeholder (over a 0x8000 default range) is emitted
//! so the crate still compiles; such an image would fail its measurement and
//! HALT (fail closed), never boot a monitor.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=REDOUBT_H_EXPECTED");
    println!("cargo:rerun-if-changed=build.rs");
    // Passed via `-C link-arg=-T...` (untracked by cargo); watch it to force a
    // relink on a layout change.
    println!("cargo:rerun-if-changed=link-brom.ld");

    let (hash_len, digest): (u32, [u8; 32]) = match env::var("REDOUBT_H_EXPECTED") {
        Ok(path) => {
            println!("cargo:rerun-if-changed={path}");
            let raw = fs::read(&path)
                .unwrap_or_else(|e| panic!("failed to read REDOUBT_H_EXPECTED={path}: {e}"));
            assert_eq!(
                raw.len(),
                36,
                "REDOUBT_H_EXPECTED={path} must be 36 bytes (4-byte LE length + \
                 32-byte BLAKE2s-256), got {}",
                raw.len()
            );
            let len = u32::from_le_bytes([raw[0], raw[1], raw[2], raw[3]]);
            let mut b = [0u8; 32];
            b.copy_from_slice(&raw[4..36]);
            (len, b)
        }
        Err(_) => (0x8000, [0xEEu8; 32]),
    };

    let mut out = String::from(
        "// GENERATED by crates/brom/build.rs from $REDOUBT_H_EXPECTED.\n\
         // Do not edit; produced by the `cargo xtask verilator -- measure` flow.\n",
    );
    out.push_str(&format!(
        "/// Bytes of the monitor image the BROM measures ([MON_CODE_BASE, +HASH_LEN)).\n\
         pub const HASH_LEN: usize = 0x{hash_len:x};\n"
    ));
    out.push_str("pub const H_EXPECTED: [u8; 32] = [\n");
    for chunk in digest.chunks(8) {
        out.push_str("    ");
        for b in chunk {
            out.push_str(&format!("0x{b:02x}, "));
        }
        out.push('\n');
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("h_expected_gen.rs");
    fs::write(&dest, out).expect("write h_expected_gen.rs");
}
