//! Memory-map codegen (ruling P2-2: `sim/memory_map.json` is the single
//! source of truth). This build script reads the generated JSON and emits a
//! Rust const module to `$OUT_DIR/memory_map_gen.rs`, which `pmp.rs` includes.
//!
//! Doing this in `build.rs` means region bases/sizes are NEVER hand-copied
//! into the PMP code: a drifted address is impossible — regenerate the JSON
//! (`redoubt_soc.py --emit-memory-map`) and the consts follow on the next
//! build. The parser is a tiny purpose-built scanner (no serde dependency, so
//! the host build stays dependency-free); the JSON is machine-generated with a
//! fixed key order, so scanning is robust.

use std::env;
use std::fs;
use std::path::Path;

/// Parse the first unsigned integer that appears after `key` in `hay`.
/// `key` is matched including its surrounding quotes (e.g. `"base"`), so it
/// never collides with a longer key that shares the prefix (`"base_hex"`).
fn num_after(hay: &str, key: &str) -> Option<u64> {
    let start = hay.find(key)? + key.len();
    let rest = hay[start..].trim_start_matches(|c: char| c == ':' || c.is_whitespace());
    let end = rest
        .find(|c: char| !c.is_ascii_digit())
        .unwrap_or(rest.len());
    rest.get(..end)?.parse().ok()
}

/// Base + size of a named region, scoped by locating its `"name": "NAME"` key
/// and reading the `"base"`/`"size"` that follow inside that object.
fn region(json: &str, name: &str) -> Option<(u64, u64)> {
    let needle = format!("\"name\": \"{name}\"");
    let idx = json.find(&needle)?;
    let seg = &json[idx..];
    let base = num_after(seg, "\"base\"")?;
    let size = num_after(seg, "\"size\"")?;
    Some((base, size))
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let map_path = Path::new(&manifest).join("../../sim/memory_map.json");
    println!("cargo:rerun-if-changed={}", map_path.display());
    println!("cargo:rerun-if-changed=build.rs");
    // The linker scripts are passed via `-C link-arg=-T...` (not tracked by cargo
    // as compilation inputs), so a script-only edit would otherwise reuse a stale
    // link. Watch them here to force a relink when their layout changes.
    println!("cargo:rerun-if-changed=link-sim.ld");
    println!("cargo:rerun-if-changed=link-qemu.ld");

    let json = fs::read_to_string(&map_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", map_path.display()));

    let mut out = String::new();
    out.push_str(
        "// GENERATED by crates/monitor-bin/build.rs from sim/memory_map.json.\n\
         // Do not edit; regenerate via `redoubt_soc.py --emit-memory-map`.\n\n",
    );

    let reset = num_after(&json, "\"reset_address\"").expect("reset_address");
    // Scope the CSR sub-object so `"base"` resolves to the CSR window base.
    let csr_idx = json.find("\"csr\"").expect("csr object");
    let csr_seg = &json[csr_idx..];
    let csr_base = num_after(csr_seg, "\"base\"").expect("csr.base");
    let uart_rxtx = num_after(csr_seg, "\"uart_rxtx\"").expect("csr.uart_rxtx");
    let uart_txfull = num_after(csr_seg, "\"uart_txfull\"").expect("csr.uart_txfull");

    // Phase-2 V4: the egress record mock's CSR layout (single-sourced from the
    // generator; redoubt_soc.py asserts LiteX placed the CSRs exactly here).
    let egress_rec = num_after(csr_seg, "\"egress_rec\"").expect("csr.egress_rec");
    let egress_words = num_after(csr_seg, "\"egress_words\"").expect("csr.egress_words");
    let egress_len = num_after(csr_seg, "\"egress_len\"").expect("csr.egress_len");
    let egress_calls = num_after(csr_seg, "\"egress_calls\"").expect("csr.egress_calls");
    out.push_str(&format!("pub const EGRESS_REC: u32 = 0x{egress_rec:08x};\n"));
    out.push_str(&format!("pub const EGRESS_WORDS: u32 = {egress_words};\n"));
    out.push_str(&format!("pub const EGRESS_LEN: u32 = 0x{egress_len:08x};\n"));
    out.push_str(&format!("pub const EGRESS_CALLS: u32 = 0x{egress_calls:08x};\n"));

    out.push_str(&format!("pub const RESET_ADDRESS: u32 = 0x{reset:08x};\n"));
    out.push_str(&format!("pub const CSR_BASE: u32 = 0x{csr_base:08x};\n"));
    out.push_str(&format!("pub const UART_RXTX: u32 = 0x{uart_rxtx:08x};\n"));
    out.push_str(&format!("pub const UART_TXFULL: u32 = 0x{uart_txfull:08x};\n\n"));

    // Every canonical region → BASE / SIZE / END consts.
    for name in [
        "BROM",
        "MON_CODE",
        "MON_DATA",
        "SECRETS",
        "EGRESS_MMIO",
        "WARDEN",
        "SHARED_REQ",
        "COMPT_0",
    ] {
        let (base, size) = region(&json, name)
            .unwrap_or_else(|| panic!("region {name} not found in memory_map.json"));
        let end = base + size;
        out.push_str(&format!("pub const {name}_BASE: u32 = 0x{base:08x};\n"));
        out.push_str(&format!("pub const {name}_SIZE: u32 = 0x{size:08x};\n"));
        out.push_str(&format!("pub const {name}_END: u32 = 0x{end:08x};\n"));
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("memory_map_gen.rs");
    fs::write(&dest, out).expect("write memory_map_gen.rs");
}
